---
title: "CMIP6_NorthAmerica_rasterprep"
output: html_document
date: '2022-06-21'
editor_options: 
  chunk_output_type: console
---


## be sure to run all this before starting
```{r setup, include=FALSE}
library(raster)
library(tidyverse)
#install.packages("terra")


all_files <- expand.grid(scenario = c("ssp126", "ssp245", "ssp370", "ssp585"),
                         years = c("2001-2020", "2021-2040", "2041-2060", "2061-2080", "2081-2100"),
                         months = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"))


```


For each month calculate wetbulb temp.
```{r}

scenario="ssp126"
years = "2001-2020"

wetbulb_fun <- function(scen=scenario, yrs=years){
months <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")

for(month in months){ # month = months[1]
  Tmax = raster(sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/NA_cmip_tiff/13GCMs_ensemble_%s_%sM_Tmax%s.tif", scen, yrs, month))
  rh = raster(sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/NA_cmip_tiff/13GCMs_ensemble_%s_%sM_RH%s.tif", scen, yrs, month))
  
  Tmax_cor <- Tmax*0.1

  Tw = Tmax_cor * atan(0.151977 * (rh + 8.313659)^(1/2)) + atan(Tmax_cor + rh) - atan(rh - 1.676331) + 0.00391838*(rh)^(3/2) * atan(0.023101 * rh) - 4.686035

  
  writeRaster(Tw, 
              sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_monthly/wb_%s_%s_%s.tif", scen, yrs, month), 
              overwrite=TRUE)
  
}}

all_files

all_files_scen_yrs <- all_files %>%
  select(scenario, years) %>%
  unique()


for(row in 1:length(all_files_scen_yrs$scenario)){ # row = 12
  cat(row)
scenario= all_files_scen_yrs$scenario[row]
years = all_files_scen_yrs$years[row]
wetbulb_fun(scen=scenario, yrs=years)
}


```

Rescale
```{r}
# Cat: change these values to adjust scaling:
pressure_zero <- 28
pressure_one <- 32.5

wb_months <- list.files("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_monthly", full=TRUE)
wb_months <- grep(".aux.xml", wb_months, invert=TRUE, value=TRUE)

# then run all this:
for(row in 1:length(wb_months)){ #row=6

wb <- wb_months[row]
wb_name <- basename(wb)
wb_raster <- terra::rast(wb)
  
wb_raster[wb_raster <= pressure_zero] <- pressure_zero
wb_raster[wb_raster >= (pressure_one)] <- pressure_one

rescaled_rast <- (wb_raster - pressure_zero)/(pressure_one - pressure_zero)

terra::writeRaster(rescaled_rast, 
                   sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_monthly_rescaled/rescaled_%s", wb_name), overwrite=TRUE)
}

current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_monthly_rescaled/rescaled_wb_ssp126_2001-2020_07.tif")
plot(current, main="July 2001-2020")

future <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_monthly_rescaled/rescaled_wb_ssp585_2081-2100_07.tif")
plot(future, main="July ssp585_2081-2100")

```


Sum rescaled wet bulb for all months within a scenario/year.
```{r}
all_files
row = 1

for(row in 1:length(all_files_scen_yrs$scenario)){
scenario= all_files_scen_yrs$scenario[row]
years = all_files_scen_yrs$years[row]

scenario_yr <- paste(scenario, years, sep="_")

scen_yr_rasts <- list.files("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_monthly_rescaled",
           pattern = scenario_yr, full=TRUE)

scen_yr_stack <- terra::rast(scen_yr_rasts)
scen_yr_sum <- terra::app(scen_yr_stack, sum, na.rm=TRUE)

terra::writeRaster(scen_yr_sum, 
                   sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled/rescaled_wb_%s.tif", scenario_yr), overwrite=TRUE)
}

future <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled/rescaled_wb_ssp585_2081-2100.tif")
plot(future, main="ssp585_2081-2100")
current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled/rescaled_wb_ssp585_2001-2020.tif")
plot(current, main="ssp585_2001-2020")

diff <- future - current
plot(diff, main = "future - current")


```

Rescale again
```{r}
# Cat: change these values to adjust scaling:
pressure_zero <- 0
pressure_one <- 6

wb_rescaled <- list.files("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled", full=TRUE)

# then run all this:
for(wb in wb_rescaled){ #wb = wb_rescaled[1]

wb_name <- basename(wb)
wb_raster <- terra::rast(wb)
  
wb_raster[wb_raster <= pressure_zero] <- pressure_zero
wb_raster[wb_raster >= (pressure_one)] <- pressure_one

rescaled_rast <- (wb_raster - pressure_zero)/(pressure_one - pressure_zero)

terra::writeRaster(rescaled_rast, 
                   sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled_rescaled/final_%s", wb_name), overwrite=TRUE)
}

current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled_rescaled/final_rescaled_wb_ssp126_2001-2020.tif")
plot(current, main="2001-2020")

future <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled_rescaled/final_rescaled_wb_ssp585_2081-2100.tif")
plot(future, main="July ssp585_2081-2100")

```

## CRS and resolution
```{r}

# spatial template
template <- raster("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/mapping_aquaculture/aquaculture_location.tif")

wb_rasters <- list.files("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled_rescaled", full=TRUE)
 #tmp <- area(raster(wb_rasters[1]))

# in this case we are going from a higher resolution raster to a lower resolution raster
# I think bilinear interpolation will be better here.

for(wb in wb_rasters){ # wb = wb_rasters[1]
  wb_rast <- raster(wb)
  filename = gsub("final_rescaled_", "", basename(wb))
  projectRaster(wb_rast, template, method="bilinear", 
                        filename = sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/wet_bulb/temp_wb_year_rescaled_rescaled_crs/%s", filename), overwrite=TRUE)

}
```
