---
title: "Average temperature"
output: html_document
date: '2022-07-07'
editor_options: 
  chunk_output_type: console
---
  
Purpose: Make a thermal pressure maps for fish classes.

## be sure to run all this before starting
```{r setup, include=FALSE}
library(raster)
library(tidyverse)
library(here)
#install.packages("terra")

## change temperature data and stocks in this spreadsheet:
tolerances <- read_csv(here("pressure_prep/data_inputs/thermal_tolerance.csv"))

all_files <- expand.grid(scenario = c("ssp126", "ssp245", "ssp370", "ssp585"),
                         years = c("2001-2020", "2021-2040", "2041-2060", "2061-2080", "2081-2100"),
                         stock = tolerances$stock)


```


For each month rescale average temperature.
```{r}

# testing
#scenario="ssp126"
#years = "2001-2020"
#stock = "carp"

## this is a function

taxa_temp_pressure <- function(scen=scenario, yrs=years,
                                fish_stock = stock){

stock_temps <- filter(tolerances, stock==fish_stock)    
t1 = stock_temps %>% pull(low_growth_limit)
t2 = stock_temps %>% pull(low_opt)
t3 = stock_temps %>% pull(high_opt)
t4 = stock_temps %>% pull(high_growth_limit)
overwinter = stock_temps %>% pull(overwinter)
  
months <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")

for(month in months){ # month = months[1]

    temp <- terra::rast(sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/NA_cmip_tiff/13GCMs_ensemble_%s_%sM_Tave%s.tif", scen, yrs, month))

    temp_water <- temp*0.1
    
  # do the high temps
     temp_high <- temp_water
    temp_high[temp_high <= t3] <- NA
    temp_high[temp_high >= t4] <- t4

    temp_high_rescale <- (temp_high - t3)/(t4 - t3)

    terra::writeRaster(temp_high_rescale, 
              sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_monthly/hot_rescale_%s_%s_%s_%s.tif", fish_stock, scen, yrs, month), 
              overwrite=TRUE)
  
    
  # do the low temps
    temp_low <- temp_water
    temp_low[temp_low >= t2] <- NA
    temp_low[temp_low <= t1] <- t1
  
    temp_low_rescale <- (temp_low - t2)/(t1 - t2)

  terra::writeRaster(temp_low_rescale, 
              sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_monthly/cold_rescale_%s_%s_%s_%s.tif", fish_stock, scen, yrs, month), 
              overwrite=TRUE)

}}

all_files

# now run the function!
for(row in 1:length(all_files$scenario)){ # row = 12
  cat(row)
stock = all_files$stock[row]
scenario = all_files$scenario[row]
years = all_files$years[row]

taxa_temp_pressure(scen=scenario, yrs=years, fish_stock = stock)
}

heat <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_monthly/hot_rescale_carp_ssp585_2001-2020_01.tif")
plot(heat, main="carp, january ssp585 2001-2020")

cold <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_monthly/cold_rescale_carp_ssp585_2041-2060_07.tif")
plot(cold, main="carp, july ssp585 2041-2060")


```

Combine monthly cold/hot temperature pressures to get yearly pressure score based on number of months needed for harvest.
```{r}

for(row in 1:length(all_files$scenario)){ # row=101

scenario = all_files$scenario[row]
years = all_files$years[row]
stock = all_files$stock[row]

scenario_yr <- paste(scenario, years, sep="_")

overwinter <- tolerances[tolerances$stock==stock, "overwinter"] %>% pull()
rear_time <- tolerances[tolerances$stock==stock, "harvest_time"] %>% pull()
rear_time <- ifelse(rear_time >= 12, 12, rear_time)

## sum cold pressures
cold_rasts <- list.files("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_monthly",
           pattern = scenario_yr, full=TRUE)
cold_rasts <- grep(stock, cold_rasts, value=TRUE)
cold_rasts <- grep("cold_rescale", cold_rasts, value=TRUE)
cat(length(cold_rasts))
cold_stack <- terra::rast(cold_rasts)
cold_sum <- terra::app(cold_stack, sum, na.rm=TRUE)

#if(overwinter=="y"){
#cold_pressure_zero = 12 - rear_time 
#cold_pressure_one <- 6
#cold_sum[cold_sum <= cold_pressure_zero] <- cold_pressure_zero
#cold_sum[cold_sum >= (cold_pressure_one)] <- cold_pressure_one
#}else{
cold_pressure_zero = 12 - rear_time
cold_pressure_one <- (12 - rear_time) +1  #add 1- 3 for buffer for sensitivity testing.
cold_sum[cold_sum <= cold_pressure_zero] <- cold_pressure_zero
cold_sum[cold_sum >= (cold_pressure_one)] <- cold_pressure_one
#}

cold_rescale <- (cold_sum - cold_pressure_zero)/(cold_pressure_one - cold_pressure_zero)


## heat pressure a function of how long it takes stock to develop

heat_rasts <- list.files("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_monthly",
           pattern = scenario_yr, full=TRUE)
heat_rasts <- grep(stock, heat_rasts, value=TRUE)
heat_rasts <- grep("hot_rescale", heat_rasts, value=TRUE)
cat(length(heat_rasts))

heat_stack <- terra::rast(heat_rasts)
heat_sum <- terra::app(heat_stack, sum, na.rm=TRUE)


hot_pressure_zero = 12 - rear_time
hot_pressure_one = hot_pressure_zero +1 #add 1- 3 for buffer for sensitivity testing

heat_sum[heat_sum <= hot_pressure_zero] <- hot_pressure_zero
heat_sum[heat_sum >= (hot_pressure_one)] <- hot_pressure_one

heat_rescale <- (heat_sum - hot_pressure_zero)/(hot_pressure_one - hot_pressure_zero)

total_pressure <- terra::app(c(cold_rescale, heat_rescale), sum, na.rm=TRUE)
total_pressure[total_pressure > 1] <- 1

terra::writeRaster(total_pressure, 
                  sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/%s_Tavg_%s.tif", stock, scenario_yr), overwrite=TRUE)
}


```

looking through the fishes to see if they make biological sense.
```{r checking}
current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/trout_Tavg_ssp585_2001-2020.tif")
plot(current, main="trout 2001-2020")

ssp2<- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/trout_Tavg_ssp245_2041-2060.tif")
plot(ssp2, main="trout ssp2 2041-2060")

ssp5 <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/trout_Tavg_ssp585_2041-2060.tif")
plot(future, main="trout ssp5 2041-2060")


current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/tilapia_Tavg_ssp585_2001-2020.tif")
plot(current, main="tilapia 2001-2020")

ssp2<- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/tilapia_Tavg_ssp245_2041-2060.tif")
plot(ssp2, main="tilapia ssp2 2041-2060")

ssp5 <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/tilapia_Tavg_ssp585_2081-2100.tif")
plot(ssp5, main="tilapia ssp5 2041-2060")

current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/carp_Tavg_ssp585_2001-2020.tif")
plot(current, main="carp 2001-2020")

ssp2<- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/carp_Tavg_ssp245_2041-2060.tif")
plot(ssp2, main="carp ssp2 2041-2060")

ssp5 <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/carp_Tavg_ssp585_2041-2060.tif")
plot(ssp5, main="carp ssp5 2041-2060")

current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/catfish_Tavg_ssp585_2001-2020.tif")
plot(current, main="catfish 2001-2020")

ssp2<- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/catfish_Tavg_ssp245_2041-2060.tif")
plot(ssp2, main="catfish ssp2 2041-2060")

ssp5 <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/catfish_Tavg_ssp585_2081-2100.tif")
plot(ssp5, main="catfish ssp5 2041-2060")

current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/perch_Tavg_ssp585_2001-2020.tif")
plot(current, main="perch 2001-2020")

ssp2<- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/perch_Tavg_ssp245_2041-2060.tif")
plot(ssp2, main="perch ssp2 2041-2060")

ssp5 <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/perch_Tavg_ssp585_2081-2100.tif")
plot(ssp5, main="perch ssp5 2041-2060")

current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/sturgeon_Tavg_ssp585_2001-2020.tif")
plot(current, main="sturgeon 2001-2020")

ssp2<- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/sturgeon_Tavg_ssp245_2041-2060.tif")
plot(ssp2, main="sturgeon ssp2 2041-2060")

ssp5 <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/sturgeon_Tavg_ssp585_2081-2100.tif")
plot(ssp5, main="sturgeon ssp5 2041-2060")

current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/bass_Tavg_ssp245_2001-2020.tif")
plot(current, main="bass 2001-2020")

ssp2<- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/bass_Tavg_ssp245_2041-2060.tif")
plot(ssp2, main="bass ssp2 2041-2060")

ssp5 <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/bass_Tavg_ssp585_2081-2100.tif")
plot(ssp5, main="bass ssp5 2041-2060")

#install.packages("USAboundariesData", repos = "https://ropensci.r-universe.dev", type = "source")
#library(USAboundaries)
states <- us_states()
plot(states, add=TRUE, color=NA, border="black", lwd=0.1)

diff <- future - current
plot(diff, main = "future - current")


```

## CRS and resolution
```{r}

# spatial template
template <- raster("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/mapping_aquaculture/aquaculture_location.tif")

temp_rasters <- list.files("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly/", full=TRUE)
 #tmp <- area(raster(wb_rasters[1]))

# in this case we are going from a higher resolution raster to a lower resolution raster
# I think bilinear interpolation will be better here.

for(temp in temp_rasters){ # temp = temp_rasters[1]
  temp_rast <- raster(temp)
  filename = basename(temp)
  projectRaster(temp_rast, template, method="bilinear", 
                        filename = sprintf("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly_crs/%s", filename), overwrite=TRUE)

}

current <- terra::rast("/home/shares/aquaculture/aquaculture_climatechange_usa/prep_data/freshwater/Tavg_taxa_prs/rescaled_yearly_crs/carp_Tavg_ssp585_2001-2020.tif")
plot(current, main="carp 2001-2020")

```
